# Generated by Django 6.0.1 on 2026-09-18 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='Date de debut')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_courante', models.BooleanField(default=False, help_text='Une seule annee academique peut etre marquee comme courante. Elle sert de valeur par defaut pour la validite des nouveaux comptes etudiants.', verbose_name='Annee courante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
            ],
            options={
                'verbose_name': 'Annee academique',
                'verbose_name_plural': 'Annees academiques',
                'ordering': ['-date_debut'],
            },
        ),
    ]
