# Generated by Django 6.0.1 on 2026-03-25 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la spécialité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.ForeignKey(help_text='Uniquement M1, M2 ou DOCTORAT.', on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='niveau.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['niveau__name', 'name'],
                'unique_together': {('name', 'niveau')},
            },
        ),
    ]
