# Generated by Django 6.0.1 on 2026-04-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niveau', '0001_initial'),
        ('specialites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialite',
            name='niveau',
            field=models.ForeignKey(help_text='Uniquement L1, L2, L3, M1, M2, DOCTORAT.', on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='niveau.niveau', verbose_name='Niveau'),
        ),
    ]
