# Generated by Django 6.0.1 on 2026-03-24 23:03

import apps.users.models.user_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favoris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueActionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Historique Action (MongoDB)',
                'verbose_name_plural': 'Historiques Actions (MongoDB)',
                'managed': False,
                'proxy': True,
            },
            bases=('favoris.favori',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('auteur', models.CharField(blank=True, help_text='Pour Memoire et These.', max_length=200, verbose_name='Auteur')),
                ('encadreur', models.CharField(blank=True, help_text="Pour Cours ou Sujet d'examen.", max_length=200, verbose_name='Encadreur / Sujet')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('type', models.CharField(choices=[('EXAMEN', 'Examen'), ('MEMOIRE', 'Memoire'), ('THESE', 'These'), ('COURS', 'Cours')], max_length=20, verbose_name='Type de document')),
                ('file_path', models.FileField(upload_to=apps.users.models.user_models.document_file_upload_path, verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoute le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
