# Generated by Django 6.0.1 on 2026-03-24 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('filiere', '0001_initial'),
        ('niveau', '0001_initial'),
        ('ue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='Ajoute par'),
        ),
        migrations.AddField(
            model_name='document',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='filiere.filiere', verbose_name='Filiere'),
        ),
        migrations.AddField(
            model_name='document',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='niveau.niveau', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='document',
            name='ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ue.ecue', verbose_name='UE concernee'),
        ),
    ]
