# Generated by Django 6.0.1 on 2026-03-25 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('specialites', '0001_initial'),
        ('ue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='specialite',
            field=models.ForeignKey(blank=True, help_text="Spécialité M1/M2/DOCTORAT du document. NULL pour les documents du tronc commun (L1/L2/L3) — dans ce cas le niveau est déduit via l'UE.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='specialites.specialite', verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ue.ecue', verbose_name='ECUE concernee'),
        ),
    ]
