# Generated by Django 6.0.1 on 2026-04-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_specialite_alter_document_ue"),
        ("specialites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="specialite",
            field=models.ForeignKey(
                blank=True,
                help_text="Spécialité L1, L2, L3, M1, M2, DOCTORAT du document.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="specialites.specialite",
                verbose_name="Spécialité",
            ),
        ),
    ]
