# Generated by Django 6.0.1 on 2026-04-02 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='annee_academique_debut',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text="Saisir l'annee de debut. Ex: 2024 pour 2024-2025. Les archives anciennes comme 1960-1961 sont aussi supportees.", null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9998)], verbose_name='Annee academique (debut)'),
        ),
    ]
