# Generated by Django 6.0.1 on 2026-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_typedocument_ordre_niveaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='auteur',
            field=models.CharField(blank=True, help_text='Auteur du document (nom du redacteur, professeur ou etudiant).', max_length=200, verbose_name='Auteur'),
        ),
    ]
