# Generated by Django 6.0.1 on 2026-09-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_document_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, editable=False, help_text='Calculee automatiquement a chaque sauvegarde a partir du fichier reellement stocke (PERF-001, evite un appel disque a chaque lecture).', null=True, verbose_name='Taille du fichier (octets)'),
        ),
    ]
