# Generated by Django 6.0.1 on 2026-03-24 22:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niveau', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code UE')),
                ('name', models.CharField(max_length=200, verbose_name='Intitule')),
                ('coef', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Coefficient total de l'UE, calcule a partir des ECUE.", max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coefficient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('niveaux', models.ManyToManyField(blank=True, related_name='ues', to='niveau.niveau', verbose_name='Niveaux concernes')),
            ],
            options={
                'verbose_name': "Unite d'Enseignement",
                'verbose_name_plural': "Unites d'Enseignement",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='Code ECUE')),
                ('name', models.CharField(max_length=200, verbose_name='Intitule ECUE')),
                ('coef', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coefficient ECUE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecues', to='ue.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'ECUE',
                'verbose_name_plural': 'ECUE',
                'ordering': ['ue__code', 'code'],
                'unique_together': {('ue', 'code')},
            },
        ),
    ]
