# Generated by Django 6.0.1 on 2026-03-25 09:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_consultation', models.CharField(choices=[('VUE', 'Vue du document'), ('RECHERCHE', 'Recherche effectuée')], max_length=20, verbose_name='Type de consultation')),
                ('recherche_query', models.CharField(blank=True, help_text='Renseigné uniquement pour le type RECHERCHE.', max_length=500, verbose_name='Terme recherché')),
                ('debut_consultation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début de consultation')),
                ('fin_consultation', models.DateTimeField(blank=True, null=True, verbose_name='Fin de consultation')),
                ('duree_secondes', models.PositiveIntegerField(blank=True, help_text='Calculée automatiquement si début et fin sont renseignés.', null=True, verbose_name='Durée (secondes)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent (navigateur)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('document', models.ForeignKey(blank=True, help_text='Renseigné uniquement pour le type VUE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='documents.document', verbose_name='Document consulté')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='consultatio_user_id_f2d174_idx'), models.Index(fields=['document', 'created_at'], name='consultatio_documen_3d546a_idx'), models.Index(fields=['type_consultation'], name='consultatio_type_co_6547a3_idx')],
            },
        ),
    ]
