# Generated by Django 6.0.1 on 2026-03-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('favoris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_en_favori_par', to='documents.document', verbose_name='Document'),
        ),
    ]
