# Generated by Django 6.0.1 on 2026-03-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favoris', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='users.etudiant', verbose_name='Étudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('etudiant', 'document')},
        ),
    ]
