# Generated by Django 6.0.1 on 2026-03-24 23:03

import apps.users.models.user_models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filiere', '0001_initial'),
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('matricule', models.CharField(blank=True, help_text='Généré automatiquement pour les étudiants.', max_length=20, null=True, unique=True, verbose_name='Matricule étudiant')),
                ('phone', models.CharField(max_length=17, unique=True, verbose_name='Téléphone')),
                ('user_type', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('BIBLIOTHECAIRE', 'Bibliothécaire'), ('ADMINISTRATEUR', 'Administrateur')], default='ETUDIANT', max_length=20, verbose_name="Type d'utilisateur")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_models.user_avatar_upload_path, verbose_name='Photo de profil')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('totp_secret', models.CharField(blank=True, help_text="Clé base32 générée lors de l'activation du 2FA.", max_length=64, null=True, verbose_name='Secret TOTP (Google Authenticator)')),
                ('is_2fa_enabled', models.BooleanField(default=False, help_text='Obligatoire pour Admin et Bibliothécaire.', verbose_name='2FA activé')),
                ('totp_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification TOTP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peut_gerer_documents', models.BooleanField(default=True, verbose_name='Gérer les documents')),
                ('peut_gerer_utilisateurs', models.BooleanField(default=False, verbose_name='Gérer les utilisateurs')),
                ('badge_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de badge')),
                ('date_prise_poste', models.DateField(blank=True, null=True, verbose_name='Date de prise de poste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'BIBLIOTHECAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_bibliothecaire', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Bibliothécaire',
                'verbose_name_plural': 'Bibliothécaires',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee_inscription', models.PositiveIntegerField(default=2026, verbose_name="Année d'inscription")),
                ('compte_active_le', models.DateTimeField(blank=True, help_text='Date de la dernière activation ou réactivation. Le compte expire 30 jours après cette date.', null=True, verbose_name='Dernière activation du compte')),
                ('compte_expire_le', models.DateTimeField(blank=True, help_text='Calculée automatiquement : compte_active_le + 30 jours.', null=True, verbose_name="Date d'expiration du compte")),
                ('nb_reactivations', models.PositiveIntegerField(default=0, help_text='Compteur historique de toutes les réactivations.', verbose_name='Nombre de réactivations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('derniere_reactivation_par', models.ForeignKey(blank=True, help_text='Admin ou Bibliothécaire ayant effectué la dernière réactivation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Dernière réactivation par')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='filiere.filiere', verbose_name='Filière')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='niveau.niveau', verbose_name='Niveau')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenBlacklist',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.CharField(max_length=255, unique=True, verbose_name='JTI du token')),
                ('revoked_at', models.DateTimeField(auto_now_add=True, verbose_name='Révoqué le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token révoqué',
                'verbose_name_plural': 'Tokens révoqués',
                'ordering': ['-revoked_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('type_code', models.CharField(choices=[('activation', 'Activation de compte'), ('password_reset', 'Réinitialisation mot de passe'), ('email_change', "Changement d'email"), ('code_OTP', 'Code OTP (2FA email)')], max_length=20, verbose_name='Type de code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de destination')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max tentatives')),
                ('expires_at', models.DateTimeField(verbose_name='Expire à')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_verification', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code de vérification',
                'verbose_name_plural': 'Codes de vérification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type_code', 'is_used'], name='users_codev_user_id_4b7a34_idx'), models.Index(fields=['code', 'email'], name='users_codev_code_a2e086_idx')],
            },
        ),
    ]
