# Generated by Django 6.0.1 on 2026-03-25 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialites', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='specialite',
            field=models.ForeignKey(blank=True, help_text='Renseigner pour M1, M2 et DOCTORAT. Laisser vide pour L1, L2 et L3.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='specialites.specialite', verbose_name='Specialite'),
        ),
    ]
