# Generated by Django 6.0.1 on 2026-03-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_etudiant_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matricule',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, help_text='Généré automatiquement pour les étudiants.', max_length=20, null=True, unique=True, verbose_name='Matricule étudiant'),
        ),
    ]
