# Generated by Django 6.0.1 on 2026-04-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialites", "0002_alter_specialite_niveau"),
        ("users", "0003_remove_user_matricule_etudiant_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="specialite",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigner pour L1, L2, L3, M1, M2, DOCTORAT.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etudiants",
                to="specialites.specialite",
                verbose_name="Specialite",
            ),
        ),
    ]
