# Generated by Django 6.0.1 on 2026-04-13 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_etudiant_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Obligatoire pour les etudiants, bibliothecaires et administrateurs.', verbose_name='2FA activé'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('PERSONNE_EXTERNE', 'Personne externe'), ('BIBLIOTHECAIRE', 'Bibliothécaire'), ('ADMINISTRATEUR', 'Administrateur')], default='ETUDIANT', max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.CreateModel(
            name='PersonneExterne',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_piece', models.CharField(blank=True, max_length=100, verbose_name='Numero de piece')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profession')),
                ('lieu_habitation', models.CharField(blank=True, max_length=255, verbose_name="Lieu d'habitation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'PERSONNE_EXTERNE'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_personne_externe', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Personne externe',
                'verbose_name_plural': 'Personnes externes',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
