# Generated by Django 6.0.1 on 2026-04-15 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiere', '0001_initial'),
        ('users', '0005_alter_user_is_2fa_enabled_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='activation_suspendue',
            field=models.BooleanField(default=False, help_text="Empêche la reactivation automatique du compte jusqu'a une nouvelle activation manuelle.", verbose_name='Activation suspendue'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_debut_validite',
            field=models.DateField(blank=True, help_text='Date a partir de laquelle le compte peut etre utilise.', null=True, verbose_name='Date de debut de validite'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_fin_validite',
            field=models.DateField(blank=True, help_text='Date de fin de validite du compte.', null=True, verbose_name='Date de fin de validite'),
        ),
        migrations.AddField(
            model_name='personneexterne',
            name='activation_suspendue',
            field=models.BooleanField(default=False, help_text="Empeche la reactivation automatique du compte jusqu'a une nouvelle activation manuelle.", verbose_name='Activation suspendue'),
        ),
        migrations.AddField(
            model_name='personneexterne',
            name='compte_active_le',
            field=models.DateTimeField(blank=True, help_text='Date a laquelle la validite du compte a ete enregistree.', null=True, verbose_name='Activation enregistree le'),
        ),
        migrations.AddField(
            model_name='personneexterne',
            name='compte_expire_le',
            field=models.DateTimeField(blank=True, help_text='Calculee automatiquement a partir de la date de fin de validite.', null=True, verbose_name="Date d'expiration du compte"),
        ),
        migrations.AddField(
            model_name='personneexterne',
            name='date_debut_validite',
            field=models.DateField(blank=True, help_text='Date a partir de laquelle le compte peut etre utilise.', null=True, verbose_name='Date de debut de validite'),
        ),
        migrations.AddField(
            model_name='personneexterne',
            name='date_fin_validite',
            field=models.DateField(blank=True, help_text='Date de fin de validite du compte.', null=True, verbose_name='Date de fin de validite'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='annee_inscription',
            field=models.PositiveIntegerField(default=2026, verbose_name="Annee d'inscription"),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='compte_active_le',
            field=models.DateTimeField(blank=True, help_text='Date de la derniere activation ou reactivation. Si une periode de validite est fournie, elle pilote la date de fin.', null=True, verbose_name='Derniere activation du compte'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='compte_expire_le',
            field=models.DateTimeField(blank=True, help_text="Calculee automatiquement a partir de la date de fin de validite, ou de la duree par defaut si aucune periode n'est configuree.", null=True, verbose_name="Date d'expiration du compte"),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='derniere_reactivation_par',
            field=models.ForeignKey(blank=True, help_text='Admin ou bibliothecaire ayant effectue la derniere reactivation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Derniere reactivation par'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='filiere.filiere', verbose_name='Filiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, help_text='Genere automatiquement pour les etudiants.', max_length=20, null=True, unique=True, verbose_name='Matricule etudiant'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nb_reactivations',
            field=models.PositiveIntegerField(default=0, help_text='Compteur historique de toutes les reactivations.', verbose_name='Nombre de reactivations'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifie le'),
        ),
    ]
