"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import Csv, config
from django.contrib.messages import constants as messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from datetime import timedelta


def env_bool(name: str, default: bool = False) -> bool:
    value = config(name, default=str(default))
    normalized = str(value).strip().lower()

    if normalized in {'1', 'true', 't', 'yes', 'y', 'on', 'debug', 'development', 'dev'}:
        return True
    if normalized in {'0', 'false', 'f', 'no', 'n', 'off', 'release', 'production', 'prod'}:
        return False

    raise ValueError(f'Invalid truth value for {name}: {value}')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=False)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # UI/UX Improvements
    'admin_interface',
    'colorfield',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_filters',
    'drf_yasg',
    'drf_spectacular',
    'safedelete',

    #Local apps
    'apps.users',
    'apps.filiere',
    'apps.niveau',
    'apps.ue',
    'apps.favoris',
    'apps.documents',
    'apps.consultations',
    'apps.history',
    'apps.specialites',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.history.middleware.RequestMetaMiddleware',
]

AUTH_USER_MODEL='users.User'
# CORS Configuration
 
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
'http://localhost:3000,http://localhost:5173,http://localhost:4200'
).split(',')
 

CORS_ALLOW_CREDENTIALS = True
# Headers autorisés
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',

]

# Configuration des sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Stockage des sessions en base de données
SESSION_COOKIE_AGE = 86400  # Durée de vie du cookie de session en secondes (1 jour)
SESSION_COOKIE_SECURE = False  # À définir sur True en production avec HTTPS
SESSION_COOKIE_HTTPONLY = True  # Empêche l'accès au cookie via JavaScript
SESSION_SAVE_EVERY_REQUEST = True  # Rafraîchit la session à chaque requête
SESSION_COOKIE_SAMESITE = 'Lax'  # Protection contre les attaques CSRF

# =============================================================================
# 🔐  DJANGO REST FRAMEWORK + JWT
# =============================================================================
 

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'E-BIBLIO API',
    'DESCRIPTION': 'Documentation API de l application E-BIBLIO',
    'VERSION': 'v1',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_GENERATE_CHOICE_DESCRIPTION': True,
    'SORT_OPERATIONS': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'list',
        'filter': True,
        'tryItOutEnabled': True,
    },
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'disableSearch': False,
        'expandResponses': '200,201',
        'requiredPropsFirst': True,
    },
}


SIMPLE_JWT = {
    # Durées
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES',  '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS',        '7'))),
 
    # Rotation
    'ROTATE_REFRESH_TOKENS':   True,
    'BLACKLIST_AFTER_ROTATION': True,   # révoque l'ancien refresh token
 
    # Claims
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
 
    # Header
    'AUTH_HEADER_TYPES': ('Bearer',),
 
    # Algorithme
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
 
    # Claims supplémentaires (user_type, matricule)
    'TOKEN_OBTAIN_SERIALIZER': 'apps.users.serializers.CustomTokenObtainPairSerializer',
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR /'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',     
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Pour PostgreSQL (optionnel)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),

        'OPTIONS': {
            'connect_timeout': 10,
        },
        'CONN_MAX_AGE': 60,   # connexions persistantes (60 sec)
    }
}


# =============================================================================
# 🍃  MONGODB — Configuration PyMongo
# =============================================================================
 
from decouple import config

MONGO_URI = config("MONGO_URI")
# URL du serveur MongoDB (ex: mongodb://localhost:27017)


MONGO_URL = config('MONGO_URI', default='mongodb://localhost:27017')

MONGODB = {
    'URI': MONGO_URL,
    'HOST': config('MONGO_HOST', default='localhost'),
    'PORT': config('MONGO_PORT', default='27017'),
    'DB': config('MONGO_DB_NAME', default='E_biblotheque'),
    'USER': config('MONGO_USER', default=''),
    'PASSWORD': config('MONGO_PASSWORD', default=''),
    'AUTH_SOURCE': config('MONGO_AUTH_SOURCE', default='admin'),
    'TTL_SECONDS': config('MONGO_TTL_SECONDS', default=15_552_000, cast=int),
    'COLLECTIONS': {
        'historique_actions': config(
            'MONGO_COLLECTION_HISTORY',
            default='historique_actions',
        ),
    },
}




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Abidjan'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# smtp
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'empotageoilsofafrica@gmail.com'  # Replace with your Gmail address
EMAIL_HOST_PASSWORD = 'vlym rhmk nmht rhge'

# =============================================================================
# 🎨  DJANGO ADMIN INTERFACE - UX/UI Improvements
# =============================================================================
ADMIN_INTERFACE = {
    'name': 'E-BIBLIO Admin',
    'title': '📚 Bibliothèque Universitaire',
    'header_color': '#2c3e50',
    'title_color': '#ffffff',
    'logo': {
        'visible': True,
        'max_width': 300,
        'max_height': 100,
    },
    'favicon': {
        'visible': True,
    },
    'language_selector': True,
    'recent_actions': True,
    'bookmarks': True,
    'form_submit_sticky': True,
    'form_pagination': True,
    'show_fieldsets_as_tabs': False,
    'module_collapsing': True,
    'apps': {
        'users': {
            'icon': 'users',
            'background_color': '#3498db',
            'text_color': '#ffffff',
        },
        'documents': {
            'icon': 'book',
            'background_color': '#e74c3c',
            'text_color': '#ffffff',
        },
        'consultations': {
            'icon': 'eye',
            'background_color': '#f39c12',
            'text_color': '#ffffff',
        },
        'favoris': {
            'icon': 'star',
            'background_color': '#9b59b6',
            'text_color': '#ffffff',
        },
        'filiere': {
            'icon': 'building',
            'background_color': '#1abc9c',
            'text_color': '#ffffff',
        },
        'niveau': {
            'icon': 'layers',
            'background_color': '#34495e',
            'text_color': '#ffffff',
        },
        'specialites': {
            'icon': 'bookmark',
            'background_color': '#16a085',
            'text_color': '#ffffff',
        },
        'ue': {
            'icon': 'graduation-cap',
            'background_color': '#27ae60',
            'text_color': '#ffffff',
        },
        'history': {
            'icon': 'history',
            'background_color': '#95a5a6',
            'text_color': '#ffffff',
        },
    },
    'theme': {
        'primary_color': '#3498db',
        'secondary_color': '#2c3e50',
        'accent_color': '#e74c3c',
        'success_color': '#27ae60',
        'warning_color': '#f39c12',
        'error_color': '#e74c3c',
        'info_color': '#3498db',
        'body_background_color': '#f8f9fa',
        'body_text_color': '#2c3e50',
        'link_color': '#3498db',
        'link_hover_color': '#2980b9',
        'header_background_color': '#2c3e50',
        'header_text_color': '#ffffff',
        'header_link_color': '#ecf0f1',
        'header_link_hover_color': '#bdc3c7',
        'module_background_color': '#ffffff',
        'module_background_selected_color': '#ecf0f1',
        'module_text_color': '#2c3e50',
        'module_text_selected_color': '#2c3e50',
        'module_link_color': '#3498db',
        'module_link_hover_color': '#2980b9',
        'module_link_selected_color': '#2980b9',
        'dropdown_background_color': '#ffffff',
        'dropdown_text_color': '#2c3e50',
        'dropdown_link_color': '#3498db',
        'dropdown_link_hover_color': '#2980b9',
        'button_background_color': '#3498db',
        'button_text_color': '#ffffff',
        'button_background_hover_color': '#2980b9',
        'button_text_hover_color': '#ffffff',
        'default_button_background_color': '#95a5a6',
        'default_button_text_color': '#ffffff',
        'default_button_background_hover_color': '#7f8c8d',
        'default_button_text_hover_color': '#ffffff',
        'success_button_background_color': '#27ae60',
        'success_button_text_color': '#ffffff',
        'success_button_background_hover_color': '#229954',
        'success_button_text_hover_color': '#ffffff',
        'warning_button_background_color': '#f39c12',
        'warning_button_text_color': '#ffffff',
        'warning_button_background_hover_color': '#e67e22',
        'warning_button_text_hover_color': '#ffffff',
        'error_button_background_color': '#e74c3c',
        'error_button_text_color': '#ffffff',
        'error_button_background_hover_color': '#c0392b',
        'error_button_text_hover_color': '#ffffff',
    },
    'list_filter_dropdown': True,
    'list_filter_sticky': True,
    'list_filter_removal_links': True,
    'search_form_placeholder': 'Rechercher...',
    'date_hierarchy': True,
    'pagination': True,
    'show_all': True,
    'view_on_site': True,
    'changeform_template': 'admin_interface/change_form.html',
    'change_list_template': 'admin_interface/change_list.html',
    'delete_confirmation_template': 'admin_interface/delete_confirmation.html',
    'delete_selected_confirmation_template': 'admin_interface/delete_selected_confirmation.html',
    'object_history_template': 'admin_interface/object_history.html',
    'responsive': True,
    'responsive_iframe': True,
    'foldable_apps': True,
    'show_inlines': True,
    'raw_id_fields': True,
    'related_modal': True,
}
